# Arquivo render.yaml Final e Corrigido

services:
  # --- Serviço da Aplicação Web Django ---
  - type: web
    name: todolist-api
    env: python
    plan: free # Especifica que você quer usar o plano gratuito
    buildCommand: "bash build.sh"
    startCommand: "python manage.py migrate && gunicorn api_root.wsgi"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: todolist-db # O nome DEVE ser idêntico ao do serviço de banco de dados abaixo
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Gera uma chave segura automaticamente
      - key: PYTHON_VERSION
        value: 3.11.3 # Use a sua versão específica do Python
      - key: DEBUG
        value: False
      - key: CORS_ALLOWED_ORIGINS
        value: "https://to-dolista.netlify.app" # Sua URL do front-end

  # --- Serviço do Banco de Dados PostgreSQL ---
  - type: pserv
    name: todolist-db
    plan: free # Especifica que você quer usar o plano gratuito