services:
  # O serviço do seu Banco de Dados PostgreSQL
  - type: pserv
    name: todolist-db
    env: postgres
    postgresMajorVersion: 14

  # O serviço da sua Aplicação Web Django
  - type: web
    name: todolist-api
    env: python
    buildCommand: "bash build.sh"
    startCommand: "python manage.py migrate && gunicorn api_root.wsgi"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: todolist-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: CORS_ALLOWED_ORIGINS
        # ATUALIZAREMOS ESTE VALOR DEPOIS
        value: "https://to-dolista.netlify.app"