# Arquivo render.yaml usando a estrutura com a seção 'databases'

services:
  - type: web
    name: todolist-api
    env: python
    plan: free
    repo: https://github.com/Vithorx/API-to-do-list.git
    buildCommand: "bash build.sh"
    startCommand: "python manage.py migrate && gunicorn api_root.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase: 
          name: todolist-db 
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: DEBUG
        value: False
      - key: CORS_ALLOW_ORIGINS
        value: "https://to-dolista.netlify.app"

databases:
  - name: todolist-db
    plan: free
    databaseName: todolist_db 
    user: todolist_user