services:
  - type: web
    name: todolist-api
    env: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "python manage.py migrate && gunicorn api_root.wsgi"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql 
          name: todolist_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.5" 
      - key: DEBUG
        value: False
      - key: CORS_ALLOWED_ORIGINS
        value: "https://to-dolista.netlify.app"
        
databases:
  - type: psql 
    name: todolist_db
    plan: free
    databaseName: todolist_db
    user: postgres