# Arquivo render.yaml - Versão Final e Corrigida

services:
  # --- Serviço do Banco de Dados PostgreSQL ---
  # Definimos o banco de dados como um serviço do tipo 'pserv'
  - type: pserv
    name: todolist-db # Nome simples, em minúsculas
    plan: free

  # --- Serviço da Aplicação Web Django ---
  - type: web
    name: todolist-api
    env: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "python manage.py migrate && gunicorn api_root.wsgi"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: todolist-db # DEVE ser idêntico ao nome do serviço de banco de dados acima
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.3 # Ou a sua versão
      - key: DEBUG
        value: False
      - key: CORS_ALLOWED_ORIGINS
        value: "https://to-dolista.netlify.app" # Sua URL do front-end